"""
Converts the Škoda Auto business capability workbook into the JSON the app reads.

    python scripts/import-capability-map.py "BusCap_DM to SA mapping.xlsx"

Writes src/lib/server/data/sa-capability-map.json.

Why a script and a committed JSON rather than reading the workbook at runtime:
the capability map changes a few times a year, the app has no spreadsheet
dependency (and should not gain one for a file it reads once), and a committed
JSON makes the taxonomy reviewable in a diff. Re-run this when the workbook is
updated and commit the result.

Standard library only — an .xlsx is a zip of XML, so openpyxl is not needed.

The source of the taxonomy is the SA_GroupMapping sheet, whose columns are:

    1 Level | 2 SA L1 | 3 SA L2 | 4 SA L3 | 5 agreed action | 6-8 proposed new |
    9 Group DM L2 | 10 Group DM L3 | 11 Group DM L4

The second sheet ("group v3.3") is the Volkswagen Group domain model, and covers
only the ".5 Sales and Marketing" branch — it is the reference the SA columns were
mapped ONTO, not the map itself. Its codes are carried through as `groupRef` on
the capabilities that have one.
"""
import json
import os
import re
import sys
import zipfile
from xml.etree import ElementTree as ET

NS = '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}'
DOC_NS = '{http://schemas.openxmlformats.org/officeDocument/2006/relationships}'

SHEET = 'SA_GroupMapping'
OUT_PATH = os.path.join('src', 'lib', 'server', 'data', 'sa-capability-map.json')
PLACEHOLDERS = {'', '-', '--', 'n/a', 'N/A', 'TBD'}


def load_sheet(path, sheet_name):
    z = zipfile.ZipFile(path)

    shared = []
    if 'xl/sharedStrings.xml' in z.namelist():
        root = ET.fromstring(z.read('xl/sharedStrings.xml'))
        for si in root.findall(f'{NS}si'):
            shared.append(''.join(t.text or '' for t in si.iter(f'{NS}t')))

    wb = ET.fromstring(z.read('xl/workbook.xml'))
    rels = ET.fromstring(z.read('xl/_rels/workbook.xml.rels'))
    targets = {r.get('Id'): r.get('Target') for r in rels}

    target = None
    for sh in wb.find(f'{NS}sheets'):
        if sh.get('name') == sheet_name:
            t = targets.get(sh.get(f'{DOC_NS}id'), '')
            target = t if t.startswith('xl/') else 'xl/' + t.lstrip('/')
    if not target:
        raise SystemExit(f'sheet "{sheet_name}" not found in {path}')

    def col_index(ref):
        n = 0
        for ch in re.match(r'[A-Z]+', ref).group(0):
            n = n * 26 + (ord(ch) - 64)
        return n - 1

    rows = []
    node = ET.fromstring(z.read(target))
    for row in node.find(f'{NS}sheetData').findall(f'{NS}row'):
        cells = {}
        for c in row.findall(f'{NS}c'):
            t, v = c.get('t'), c.find(f'{NS}v')
            inline = c.find(f'{NS}is')
            if t == 's' and v is not None:
                val = shared[int(v.text)]
            elif inline is not None:
                val = ''.join(x.text or '' for x in inline.iter(f'{NS}t'))
            elif v is not None:
                val = v.text
            else:
                continue
            val = (val or '').strip()
            if val:
                cells[col_index(c.get('r'))] = val
        rows.append(cells)
    return rows


def clean(value):
    v = (value or '').strip()
    return '' if v in PLACEHOLDERS else v


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'BusCap_DM to SA mapping.xlsx'
    rows = load_sheet(src, SHEET)

    # Ordered dict of domain -> group -> [capability]; insertion order is the
    # workbook's own order, which groups related domains together and reads
    # better on the map than alphabetical would.
    domains = {}
    for cells in rows:
        level = cells.get(1)
        if not level or not str(level).isdigit():
            continue
        l1, l2, l3 = clean(cells.get(2)), clean(cells.get(3)), clean(cells.get(4))
        if not l1:
            continue

        domain = domains.setdefault(l1, {})
        if not l2:
            continue
        group = domain.setdefault(l2, {})
        if not l3:
            continue

        ref = ' / '.join(x for x in (clean(cells.get(9)), clean(cells.get(10)), clean(cells.get(11))) if x)
        group[l3] = ref or None

    out = {
        'source': f'{os.path.basename(src)} — sheet "{SHEET}"',
        'note': (
            'Generated by scripts/import-capability-map.py. Domains with no groups are '
            'level-1 stubs in the workbook: the taxonomy simply has no detail for them yet.'
        ),
        'domains': [
            {
                'name': d,
                'groups': [
                    {
                        'name': g,
                        'capabilities': [
                            {'name': c, 'groupRef': ref} for c, ref in caps.items()
                        ]
                    }
                    for g, caps in groups.items()
                ]
            }
            for d, groups in domains.items()
        ]
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, 'w', encoding='utf8') as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False)
        fh.write('\n')

    n_groups = sum(len(d['groups']) for d in out['domains'])
    n_caps = sum(len(g['capabilities']) for d in out['domains'] for g in d['groups'])
    stubs = [d['name'] for d in out['domains'] if not d['groups']]
    print(f'{OUT_PATH}: {len(out["domains"])} domains, {n_groups} groups, {n_caps} capabilities')
    if stubs:
        print(f'level-1 stubs with no detail ({len(stubs)}): {", ".join(stubs)}')


if __name__ == '__main__':
    main()
